sudo: required
services:
  - docker

before_install:
  - docker build -t wingrider/react-container -f Dockerfile.dev .

script:
  - docker run wingrider/react-container npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "react-container"
  env: "ReactContainer-env"
  bucket_name: "elasticbeanstalk-us-east-2-676121265370"
  bucket_path: "react-container"
  on:
    branch: master
  access_key_id: $AWS_EB_ACCESS
  secret_access_key:
    secure: $AWS_EB_SECRET
